### PR TITLE
Handle List of Packages in Web Server

### LINKED ISSUE #1065: Unable to use --package command when starting the webserver
### What happened?

The webserver is able to start when being provided with the '--package' command but every validation request fails with an internal server error (500). The webserver's log shows the following output:

Traceback (most recent call last):
  File "C:\Arelle-master\arelle\webserver\bottle.py", line 999, in _handle
    out = route.call(**args)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Arelle-master\arelle\webserver\bottle.py", line 2015, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Arelle-master\arelle\CntlrWebMain.py", line 301, in validation
    return runOptionsAndGetResult(options, media, viewFile, sourceZipStream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Arelle-master\arelle\CntlrWebMain.py", line 328, in runOptionsAndGetResult
    successful = cntlr.run(options, sourceZipStream, responseZipStream)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Arelle-master\arelle\CntlrCmdLine.py", line 732, in run
    if options.packages:
       ^^^^^^^^^^^^^^^^
AttributeError: 'Options' object has no attribute 'packages'

### Documents

_No response_

### If running from the command line, what command did you run?

python arelleCmdLine.py --package esef_taxonomy/esef_taxonomy_2022_v1.1.zip --package esef_taxonomy/IFRSAT-2022-03-24_0.zip --package esef_taxonomy/lei-taxonomy-REC-2020-07-02_2.zip --webserver localhost:8080  --internetConnectivity=offline

### Interface

CLI (arelleCmdLine)

### Version

2.23.1

### Download

From source (git checkout)

### Operating System

Windows 10

### PR DESCRIPTION
**Pull request by austinmatherne-wk**
#### Reason for change
Resolves #1065

#### Description of change
* Make mypy type hint checking opt-out instead of opt-in for modules.
* Add type hints to CntlrWebMain module.
* Update the webserver to handle the list format of packages introduced by #940.
* Update webserver cntrl to use standard RuntimeOptions class.

#### Steps to Test
Verify no errors are thrown from:
* Start webserver with multiple packages:
`python arelleCmdLine.py --webserver=0.0.0.0:8080 --package https://filings.xbrl.org/549300PZMFIQR79Q0T97/2023-12-31/ESEF/IS/0/549300PZMFIQR79Q0T97-2023-12-31-en.zip --package https://filings.xbrl.org/2138005WRSDC4DI3BJ43/2023-12-31/ESEF/IS/0/2138005WRSDC4DI3BJ43-2023-12-31-is.zip`
* Use configure API to load other packages:
`http://localhost:8080/rest/configure?packages=https://filings.xbrl.org/549300D2K6PKKKXVNN73/2022-12-31/ESEF/DK/0/APMM-2022-12-31-en.zip|https://filings.xbrl.org/5299008YTLEN09WTHW26/2023-12-31/ESEF/IS/0/5299008YTLEN09WTHW26-2023-12-31.zip`
* Validate with even more packages:
`http://localhost:8080/rest/xbrl/validation?plugins=validate/ESEF&disclosureSystem=esef&media=json&file=https://filings.xbrl.org/2138001CNF45JP5XZK38/2023-12-31/ESEF/FI/1/KONE-2023-12-31-en.zip&packages=https://filings.xbrl.org/2138004PXX8LWGHGL872/2023-12-31/ESEF/DK/0/2138004PXX8LWGHGL872-2023-12-31-en.zip|https://filings.xbrl.org/5299007OWYZ6I1E46843/2023-12-31/ESEF/DK/0/5299007OWYZ6I1E46843-2023-12-31-en.zip`

**review**:
@Arelle/arelle

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by aaroncameron-wk — APPROVED** [review]
