### ISSUE TITLE
Unable to use --package command when starting the webserver

### ISSUE THREAD

**Issue by bytelooper** [Arelle/Arelle#1065]
### What happened?

The webserver is able to start when being provided with the '--package' command but every validation request fails with an internal server error (500). The webserver's log shows the following output:

Traceback (most recent call last):
  File "C:\Arelle-master\arelle\webserver\bottle.py", line 999, in _handle
    out = route.call(**args)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Arelle-master\arelle\webserver\bottle.py", line 2015, in wrapper
    rv = callback(*a, **ka)
         ^^^^^^^^^^^^^^^^^^
  File "C:\Arelle-master\arelle\CntlrWebMain.py", line 301, in validation
    return runOptionsAndGetResult(options, media, viewFile, sourceZipStream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Arelle-master\arelle\CntlrWebMain.py", line 328, in runOptionsAndGetResult
    successful = cntlr.run(options, sourceZipStream, responseZipStream)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Arelle-master\arelle\CntlrCmdLine.py", line 732, in run
    if options.packages:
       ^^^^^^^^^^^^^^^^
AttributeError: 'Options' object has no attribute 'packages'

### If running from the command line, what command did you run?

python arelleCmdLine.py --package esef_taxonomy/esef_taxonomy_2022_v1.1.zip --package esef_taxonomy/IFRSAT-2022-03-24_0.zip --package esef_taxonomy/lei-taxonomy-REC-2020-07-02_2.zip --webserver localhost:8080  --internetConnectivity=offline

### Interface

CLI (arelleCmdLine)

### Version

2.23.1

### Download

From source (git checkout)

### Operating System

Windows 10

**Comment by paulwarren-wk** [comment]
I think this was introduced by https://github.com/Arelle/Arelle/pull/940 because the `packages` option  became an array not a string, which means that if it is specified, it doesn't get copied across by the code here:

https://github.com/Arelle/Arelle/blob/master/arelle/CntlrWebMain.py#L31

```python
    optionsPrototype = dict((option,value if isinstance(value, STR_NUM_TYPES) else None)
                            for option in dir(options)
                            for value in (getattr(options, option),)
                            if isinstance(value,optionValuesTypes) and not option.startswith('_'))
```

I think we need to include `list` types into what gets copied across, but I don't really understand what this code is trying to filter out that isn't already filtered out by checking for options starting with `_`.

Removing the type filter, and permitting list types doesn't obviously break things, and appears to resolve the above issue: 

```python
    optionsPrototype = dict((option,value if isinstance(value, STR_NUM_TYPES + (list,)) else None)
                            for option in dir(options)
                            for value in (getattr(options, option),)
                            if not option.startswith('_'))
```

**Comment by bytelooper** [comment]
@paulwarren-wk your fix seems to be working fine, any update on when this will be part of the next release?
